version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "deps(ci): "
    labels:
      - dependencies
      - github_actions
    groups:
      codeql-action:
        patterns:
          - github/codeql-action*

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "deps(go): "
    labels:
      - dependencies
      - go
